### ISSUE TITLE
la RAZ d'un user ne fonctionne pas si celui-ci contient une majuscule

### ISSUE THREAD

**Issue by edouard-gv** [Arnauld/extreme-carpaccio-java-server#3]
J'ai une NPE quand j'appelle /admin/reset/pwd/player ou quand j'appelle /admin/resetall/pwd des que le player commence par une majuscule.

J'ai contourné en ajoutant un toLowerCase() à username ligne 109 de InMemoryPlayer. Mais y a plus propre sûrement. Viendrait du keyOf() qui met en minuscule le nom du player en tant que clé ?

(Je ne peux pas faire de PR depuis chez mon client..., d'où l'issue :)).

**Comment by Arnauld** [comment]
une petite stacktrace peut être ?

**Comment by Arnauld** [comment]
ok effectivement https://github.com/Arnauld/extreme-carpaccio-java-server/blob/c7b6d9db61240e3ff74f053839ecc947d95a634c/src/main/java/fr/arolla/core/InMemoryPlayers.java#L109
il manque l'appel à `toLowerCase`

**Comment by Arnauld** [comment]
il faudrait remplacer par un appel à `keyOf(String)`
idem ici:
https://github.com/Arnauld/extreme-carpaccio-java-server/blob/c7b6d9db61240e3ff74f053839ecc947d95a634c/src/main/java/fr/arolla/core/InMemoryPlayers.java#L103

**Comment by Arnauld** [comment]
https://github.com/Arnauld/extreme-carpaccio-java-server/commit/ca8f2ad90ba4bd59159dfac01edc53ed1a83ec1b
