### ISSUE TITLE
Les seuils de réduction "standard" semblent incorrects

### ISSUE THREAD

**Issue by edouard-gv** [Arnauld/extreme-carpaccio-java-server#4]
D'après les spec (https://github.com/dlresende/extreme-carpaccio/blob/master/clients/README.md), les seuils sont à 1000, 5000 etc. Cela n'est pas le cas ici, du fait a priori de fautes de frappes dans la classe ReductionMode (1_0000 au lieu de 1_000 par exemple).

**Comment by Arnauld** [comment]
yep corrigé à la cowboy via l'interface web 🤠

**Comment by Arnauld** [comment]
Le mode "standard" n'a quasi pas été utilisé, on est très vite parti sur la partie scriptée (groovy)
